services:

  mysql:
    image: mysql:8.0
    container_name: mysqlDb01
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./mysql01:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - redkrystalNet001

  mongodb:
    image: mongo:latest
    container_name: mongoDb01
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    volumes:
      - ./mongo01:/data/db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - redkrystalNet001

networks:
  redkrystalNet001:
    external: true
