services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - redkrystalNet001

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - redkrystalNet001
    depends_on:
      - server

networks:
  redkrystalNet001:
    external: true
